### PR TITLE
Content and channel filters

### PR DESCRIPTION
**Pull request by marcdeb1**
This pull request is adding three more filters to the search, as talked about in issues #111 and #109.

- Filter claimType can be used to search only for files or channels. Its value can be 'channel' or 'file'.
- contentType allows filter by MIME type, according to the contentType field in the claim. For example, query 'contentType=image/png' will return only PNG images.
- mediaType is a more general filter for content. It can have 6 values : video, image, text, application, audio or cad. The first 5 types correspond to the MIME type, 'cad' maps to the 3D model types.

Please share your suggestions and comments if there are any issues.

### CODE REVIEW

**Comment by tiger5226** [comment]
I am hesitant to just keep adding parameters for search. Is there a better way to do this? What do you recommend? Also you can reach me on slack too during the day as well. I know we want to prevent having to do this. Maybe multiple apis?

**Comment by marcdeb1** [comment]
In my opinion it is okay to add parameters it is then useful in the final app, as described in the issues mentioned. Are you on Discord ? What do you mean by multiple apis ? Different endpoints ?

**Comment by tiger5226** [comment]
yeah different endpoints. I am ok with it. I just wanted to validate the change is all. I am on discord @Beamer, and on slack with the same name if you join our tech-guest channel.

**Comment by tiger5226** [comment]
@marcdeb1 what IDE are you using? Looks like linting is not turned on yet per the codacy report above. I fixed the other PR and happy to fix this one too, but if you could also turn this on that would be cool. Let me know. We use JetBrains, but if you are using something else may have to do some googling.

**Comment by marcdeb1** [comment]
Fixed, I will push something clean next time !

**Comment by tiger5226** [comment]
Thanks! looks good! You forgot to run the generate script for documentation. That updates the docs.

**Comment by marcdeb1** [comment]
Noted, I didn't know how to do this.

**Comment by tiger5226** [comment]
Thanks! Can you squash and rebase please https://github.com/lbryio/lbry/wiki/Branching-and-Merging

**Comment by marcdeb1** [comment]
A list of media types can now be given as input. Examples of queries :
- mediaType=image,cad will return all images and CAD claims.
- contentType=image/gif,video/mp4 will filter only GIFs and MP4 videos.

**Comment by tiger5226** [comment]
@tzarebczan I am going to put this branch on dev for QA. Let me know if there is a different branch we should put there 1st. I wanted to get these PRs ready to be merged.

**Comment by tzarebczan** [comment]
@tiger5226 that works for me, let's get it tested soon.

**Comment by tzarebczan** [comment]
@nikooo777 / @tiger5226 do we have a test server to deploy this on?

**Comment by nikooo777** [comment]
we have a dev server for lighthouse but until issue #142  is fixed we can't turn it back on

**Comment by tzarebczan** [comment]
@marcdeb1 we'll be focusing on discovery / search UX in the next app sprints - can we get this rolling later this week?

**Comment by tzarebczan** [comment]
doh, meant to tag @tiger5226, sorry mardeb :p

**Comment by tiger5226** [comment]
squashed and rebased into #144. closing here.

**Pull request closed without merging**
