### PR TITLE
add npm run docker-elasticsearch

### PR DESCRIPTION
**Pull request by BelfordZ**

### CODE REVIEW

**Comment by BelfordZ** [comment]
@tiger5226 yeah for sure would be good to document.

Chances are, you would want to run your own elasticsearch to dev against. This Pr gives you `npm run docker-elasticsearch` which starts it up with w.e. cli args are required.

Further improvements on this could involve some kind of pipeline like
`npm run dev`:
 - builds js with babel or w.e.
 - boots elasticsearch docker container
    - if you can boot a snapshot of the container, do that. Otherwise,
    - run sync script on the new local elasticsearch

**Comment by tiger5226** [comment]
I like the idea of docker! Especially as an initial step for a first time developer. 

I guess the main concern would be around, making sure the right steps are followed for a developer every single time and that we are doing something that helps. So for example if this is run, does it start from a fresh database each time? The last full sync I did took 40 minutes to get and index all claims in the blockchain. There are also specific ordered steps that need to be run for this to work. How are those incorporated here?

**Comment by tiger5226** [comment]
I missed the "don't have time ATM". All clear. I will keep this here as a reference for when we do something with it. If we do docker, I would want to answer the questions above, and also include kibana too.

**Comment by tiger5226** [comment]
closing PR will keep branch for reference.

**Pull request closed without merging**
